### ISSUE TITLE
It seems flask-mail dependency is broken

### ISSUE THREAD

**Issue by idchlife** [dusktreader/flask-praetorian#182]
Recently started having this errors out of the blue

```python
Error: While importing "backend.app", an ImportError was raised:

Traceback (most recent call last):
  File "/home/idchlife/.local/share/virtualenvs/backend-D_zJVBqc/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/media/idchlife/Propulsion/www/work/backend/app.py", line 11, in <module>
    from .cli import initialize_commands
  File "/media/idchlife/Propulsion/www/work/backend/cli.py", line 10, in <module>
    from .tools.common import format_phone, UPLOADS_FOLDER
  File "/media/idchlife/Propulsion/www/work/backend/tools/common.py", line 22, in <module>
    from ..models import Image, User, Store, Audit
  File "/media/idchlife/Propulsion/www/work/backend/models.py", line 8, in <module>
    from flask_praetorian import current_user
  File "/home/idchlife/.local/share/virtualenvs/backend-D_zJVBqc/lib/python3.7/site-packages/flask_praetorian/__init__.py", line 5, in <module>
    from flask_praetorian.base import Praetorian  # noqa
  File "/home/idchlife/.local/share/virtualenvs/backend-D_zJVBqc/lib/python3.7/site-packages/flask_praetorian/base.py", line 11, in <module>
    from flask_mail import Message
  File "/home/idchlife/.local/share/virtualenvs/backend-D_zJVBqc/lib/python3.7/site-packages/flask_mail.py", line 17, in <module>
    import blinker
ModuleNotFoundError: No module named 'blinker'
```

**Comment by idchlife** [comment]
NVM it was just some kind of weird flex, blinker for some reason was removed from Pipfile.
