### ISSUE TITLE
Authentication issue, encode_jwt_token returns 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by spennell** [dusktreader/flask-praetorian#230]
I recently updated versions of the project, and noticed my apps authentication isn't working.

The stacktrace points to this line being the culprit. It appears jwt.encode is returning a string  making the .decode  function redundant.

```
return jwt.encode(
    payload_parts, self.encode_key, self.encode_algorithm,
).decode('utf-8')
```

```
Traceback (most recent call last):
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 85, in sentry_patched_wsgi_app
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 129, in __call__
    reraise(*_capture_exception(hub))
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 122, in __call__
    rv = self.app(
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 85, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_restx/api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_restx/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_restx/marshalling.py", line 248, in wrapper
    resp = f(*args, **kwargs)
  File "/home/shawn/PycharmProjects/launchcenter/apis/resources.py", line 27, in post
    response = resources.login(json)
  File "/home/shawn/PycharmProjects/launchcenter/components/resources.py", line 79, in login
    token = guard.encode_jwt_token(user_obj)
  File "/home/shawn/PycharmProjects/launchcenter/venv/lib/python3.8/site-packages/flask_praetorian/base.py", line 390, in encode_jwt_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
```

It could be on my end, removing .decode('utf-8') resolves the issue. It may be due to changes in JWT, or maybe library incompatibility issues on my end. Figured I'd check here for any input.

**Comment by spennell** [comment]
After looking into PyJWT change logs for version 2.0.0 ```jwt.encode(...)``` Tokens are returned as string instead of byte string.

[https://pyjwt.readthedocs.io/en/2.0.1/changelog.html](url)

This explains the behavior.

**Comment by dusktreader** [comment]
Sorry for missing this. This issue has been addressed in the latest release of flask-praetorian (1.2.0).
