### ISSUE TITLE
AttributeError: can't set attribute in example/basic.py

### ISSUE THREAD

**Issue by BlarghAld** [dusktreader/flask-praetorian#256]
Code copied verbatim from example/basic.py; python version is 3.9.6; oddly I don't see the error in my actual work, but I needed to fire up the demo to verify a separate issue...
I have verified that downgrading SQLAlchemy makes no difference. Any help much appreciated. 

Stack trace:

D:\Unity\praet-test\venv\lib\site-packages\flask_sqlalchemy\__init__.py:872: FSADeprecationWarning: SQLALCHEMY_TRACK_MOD
IFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress
 this warning.
  warnings.warn(FSADeprecationWarning(
Traceback (most recent call last):
  File "D:\Unity\praet-test\praet.py", line 104, in <module>
    User(
  File "<string>", line 4, in __init__
  File "D:\Unity\praet-test\venv\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "D:\Unity\praet-test\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\Unity\praet-test\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "D:\Unity\praet-test\venv\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\Unity\praet-test\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1145, in _declarative_constructor
    setattr(self, k, kwargs[k])
AttributeError: can't set attribute

**Comment by pepperpepperpepper** [comment]
this is because the column is named "hashed_password" and not "password". if you set the attributes of User as so User(username="abcd", hashed_password="efgh") it will work

**Comment by dusktreader** [comment]
Fixed by PR #262
